// ticket-de-refeicao-senai/styles/ThemeStyles.js
import { StyleSheet } from "react-native";

// Centralized color palette used across the app
export const Colors = {
  primary: "#000000ff",
  onPrimary: "#ffffffff",
  background: "#ffffffff",
};

const Theme = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    // Fundo sem preencher para permitir a imagem de background transparecer
    backgroundColor: "rgba(255,255,255,0.85)",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.6)",
  },
  header: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#000000ff",
    marginBottom: 28,
    textAlign: "center",
    letterSpacing: 2,
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 12,
    textTransform: "uppercase",
    borderBottomWidth: 2,
    borderColor: "rgba(0,0,0,0.6)",
    paddingBottom: 8,
  },
  subHeader: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000ff",
    marginBottom: 12,
    textAlign: "left",
    letterSpacing: 1.2,
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.95)",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.6)",
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
    fontSize: 18,
    color: "#000000ff",
    shadowColor: "#000000ff",
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 3,
    fontFamily: "monospace",
  },
  button: {
    backgroundColor: "#000000ff",
    paddingVertical: 18,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000ff",
    shadowOpacity: 0.32,
    shadowRadius: 16,
    elevation: 7,
    marginBottom: 14,
  borderWidth: 1.5,
  borderColor: "rgba(0,0,0,0.6)",
    minWidth: 100,
    overflow: "hidden",
    // Simulação de gradiente com borda dupla
    borderTopWidth: 3.5,
    borderTopColor: "#000000ff",
    borderBottomWidth: 3.5,
    borderBottomColor: "#000000ff",
    // Efeito de "pressionado" visual (aplique scale em TouchableOpacity para animação real)
  },
  buttonText: {
    color: Colors.onPrimary,
    fontSize: 15,
    fontWeight: "bold",
    letterSpacing: 2.5,
    textTransform: "uppercase",
    fontFamily: "monospace",
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 2,
    textAlign: "center",
    paddingHorizontal: 8,
    // Efeito "glow"
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.9)",
    padding: 20,
    borderRadius: 18,
    marginBottom: 16,
    shadowColor: "#000000ff",
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.5)",
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#000000ff",
    marginBottom: 12,
    letterSpacing: 1.2,
    textShadowColor: "#ffffffff",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  cardText: {
    fontSize: 17,
    color: "#000000ff",
    letterSpacing: 0.7,
    fontFamily: "monospace",
  },
  footerText: {
    fontSize: 16,
    color: "#000000ff",
    textAlign: "center",
    marginTop: 28,
    letterSpacing: 0.7,
    fontFamily: "monospace",
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
});

export default Theme;
