// ticket-de-refeicao-senai/styles/ThemeStyles.js
import { StyleSheet } from "react-native";


const Theme = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#ffffffff",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderWidth: 2,
    borderColor: "#000000ff",
  },
  header: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#000000ff",
    marginBottom: 28,
    textAlign: "center",
    letterSpacing: 2,
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 12,
    textTransform: "uppercase",
    borderBottomWidth: 2,
    borderColor: "#000000ff",
    paddingBottom: 8,
  },
  subHeader: {
    fontSize: 22,
    fontWeight: "700",
    color: "#000000ff",
    marginBottom: 12,
    textAlign: "left",
    letterSpacing: 1.2,
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  input: {
    backgroundColor: "#ffffffff",
    borderWidth: 2,
    borderColor: "#000000ff",
    borderRadius: 18,
    padding: 16,
    marginBottom: 20,
    fontSize: 18,
    color: "#000000ff",
    shadowColor: "#000000ff",
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 3,
    fontFamily: "monospace",
  },
  button: {
    backgroundColor: "#000000ff",
    paddingVertical: 18,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000ff",
    shadowOpacity: 0.32,
    shadowRadius: 16,
    elevation: 7,
    marginBottom: 14,
    borderWidth: 2.5,
    borderColor: "#000000ff",
    minWidth: 200,
    overflow: "hidden",
    // Simulação de gradiente com borda dupla
    borderTopWidth: 3.5,
    borderTopColor: "#000000ff",
    borderBottomWidth: 3.5,
    borderBottomColor: "#000000ff",
    // Efeito de "pressionado" visual (aplique scale em TouchableOpacity para animação real)
  },
  buttonText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "bold",
    letterSpacing: 2.5,
    textTransform: "uppercase",
    fontFamily: "monospace",
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 8,
    textAlign: "center",
    paddingHorizontal: 8,
    // Efeito "glow"
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  card: {
    backgroundColor: "#ffffffff",
    padding: 24,
    borderRadius: 22,
    marginBottom: 20,
    shadowColor: "#000000ff",
    shadowOpacity: 0.13,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 2,
    borderColor: "#000000ff",
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#000000ff",
    marginBottom: 12,
    letterSpacing: 1.2,
    textShadowColor: "#ffffffff",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  cardText: {
    fontSize: 17,
    color: "#000000ff",
    letterSpacing: 0.7,
    fontFamily: "monospace",
  },
  footerText: {
    fontSize: 16,
    color: "#000000ff",
    textAlign: "center",
    marginTop: 28,
    letterSpacing: 0.7,
    fontFamily: "monospace",
    textShadowColor: "#000000ff",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
});

export default Theme;
